# Generated by Django 3.1.7 on 2021-03-23 19:36

from django.db import migrations


def create_products(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Product.objects.create(name='Laptop_1', price=225.65)
    Product.objects.create(name='Laptop_2', price=325.65)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210323_1935'),
    ]

    operations = [
        migrations.RunPython(create_products, lambda x, y: None)
    ]
